/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.acvr.order.dto;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class OrderCreated extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2779499480508105058L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderCreated\",\"namespace\":\"com.acvr.order.dto\",\"fields\":[{\"name\":\"orderId\",\"type\":\"long\"},{\"name\":\"orderDate\",\"type\":\"string\"},{\"name\":\"costomerName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"productName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"amount\",\"type\":\"double\",\"default\":0.0}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<OrderCreated> ENCODER =
      new BinaryMessageEncoder<OrderCreated>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderCreated> DECODER =
      new BinaryMessageDecoder<OrderCreated>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<OrderCreated> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<OrderCreated> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OrderCreated>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this OrderCreated to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a OrderCreated from a ByteBuffer. */
  public static OrderCreated fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long orderId;
  @Deprecated public java.lang.CharSequence orderDate;
  @Deprecated public java.lang.CharSequence costomerName;
  @Deprecated public java.lang.CharSequence productName;
  @Deprecated public double amount;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderCreated() {}

  /**
   * All-args constructor.
   * @param orderId The new value for orderId
   * @param orderDate The new value for orderDate
   * @param costomerName The new value for costomerName
   * @param productName The new value for productName
   * @param amount The new value for amount
   */
  public OrderCreated(java.lang.Long orderId, java.lang.CharSequence orderDate, java.lang.CharSequence costomerName, java.lang.CharSequence productName, java.lang.Double amount) {
    this.orderId = orderId;
    this.orderDate = orderDate;
    this.costomerName = costomerName;
    this.productName = productName;
    this.amount = amount;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orderId;
    case 1: return orderDate;
    case 2: return costomerName;
    case 3: return productName;
    case 4: return amount;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orderId = (java.lang.Long)value$; break;
    case 1: orderDate = (java.lang.CharSequence)value$; break;
    case 2: costomerName = (java.lang.CharSequence)value$; break;
    case 3: productName = (java.lang.CharSequence)value$; break;
    case 4: amount = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'orderId' field.
   * @return The value of the 'orderId' field.
   */
  public java.lang.Long getOrderId() {
    return orderId;
  }

  /**
   * Sets the value of the 'orderId' field.
   * @param value the value to set.
   */
  public void setOrderId(java.lang.Long value) {
    this.orderId = value;
  }

  /**
   * Gets the value of the 'orderDate' field.
   * @return The value of the 'orderDate' field.
   */
  public java.lang.CharSequence getOrderDate() {
    return orderDate;
  }

  /**
   * Sets the value of the 'orderDate' field.
   * @param value the value to set.
   */
  public void setOrderDate(java.lang.CharSequence value) {
    this.orderDate = value;
  }

  /**
   * Gets the value of the 'costomerName' field.
   * @return The value of the 'costomerName' field.
   */
  public java.lang.CharSequence getCostomerName() {
    return costomerName;
  }

  /**
   * Sets the value of the 'costomerName' field.
   * @param value the value to set.
   */
  public void setCostomerName(java.lang.CharSequence value) {
    this.costomerName = value;
  }

  /**
   * Gets the value of the 'productName' field.
   * @return The value of the 'productName' field.
   */
  public java.lang.CharSequence getProductName() {
    return productName;
  }

  /**
   * Sets the value of the 'productName' field.
   * @param value the value to set.
   */
  public void setProductName(java.lang.CharSequence value) {
    this.productName = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public java.lang.Double getAmount() {
    return amount;
  }

  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(java.lang.Double value) {
    this.amount = value;
  }

  /**
   * Creates a new OrderCreated RecordBuilder.
   * @return A new OrderCreated RecordBuilder
   */
  public static com.acvr.order.dto.OrderCreated.Builder newBuilder() {
    return new com.acvr.order.dto.OrderCreated.Builder();
  }

  /**
   * Creates a new OrderCreated RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderCreated RecordBuilder
   */
  public static com.acvr.order.dto.OrderCreated.Builder newBuilder(com.acvr.order.dto.OrderCreated.Builder other) {
    return new com.acvr.order.dto.OrderCreated.Builder(other);
  }

  /**
   * Creates a new OrderCreated RecordBuilder by copying an existing OrderCreated instance.
   * @param other The existing instance to copy.
   * @return A new OrderCreated RecordBuilder
   */
  public static com.acvr.order.dto.OrderCreated.Builder newBuilder(com.acvr.order.dto.OrderCreated other) {
    return new com.acvr.order.dto.OrderCreated.Builder(other);
  }

  /**
   * RecordBuilder for OrderCreated instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderCreated>
    implements org.apache.avro.data.RecordBuilder<OrderCreated> {

    private long orderId;
    private java.lang.CharSequence orderDate;
    private java.lang.CharSequence costomerName;
    private java.lang.CharSequence productName;
    private double amount;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.acvr.order.dto.OrderCreated.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.orderDate)) {
        this.orderDate = data().deepCopy(fields()[1].schema(), other.orderDate);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.costomerName)) {
        this.costomerName = data().deepCopy(fields()[2].schema(), other.costomerName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.productName)) {
        this.productName = data().deepCopy(fields()[3].schema(), other.productName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.amount)) {
        this.amount = data().deepCopy(fields()[4].schema(), other.amount);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing OrderCreated instance
     * @param other The existing instance to copy.
     */
    private Builder(com.acvr.order.dto.OrderCreated other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.orderId)) {
        this.orderId = data().deepCopy(fields()[0].schema(), other.orderId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.orderDate)) {
        this.orderDate = data().deepCopy(fields()[1].schema(), other.orderDate);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.costomerName)) {
        this.costomerName = data().deepCopy(fields()[2].schema(), other.costomerName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.productName)) {
        this.productName = data().deepCopy(fields()[3].schema(), other.productName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.amount)) {
        this.amount = data().deepCopy(fields()[4].schema(), other.amount);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'orderId' field.
      * @return The value.
      */
    public java.lang.Long getOrderId() {
      return orderId;
    }

    /**
      * Sets the value of the 'orderId' field.
      * @param value The value of 'orderId'.
      * @return This builder.
      */
    public com.acvr.order.dto.OrderCreated.Builder setOrderId(long value) {
      validate(fields()[0], value);
      this.orderId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orderId' field has been set.
      * @return True if the 'orderId' field has been set, false otherwise.
      */
    public boolean hasOrderId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orderId' field.
      * @return This builder.
      */
    public com.acvr.order.dto.OrderCreated.Builder clearOrderId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'orderDate' field.
      * @return The value.
      */
    public java.lang.CharSequence getOrderDate() {
      return orderDate;
    }

    /**
      * Sets the value of the 'orderDate' field.
      * @param value The value of 'orderDate'.
      * @return This builder.
      */
    public com.acvr.order.dto.OrderCreated.Builder setOrderDate(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.orderDate = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'orderDate' field has been set.
      * @return True if the 'orderDate' field has been set, false otherwise.
      */
    public boolean hasOrderDate() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'orderDate' field.
      * @return This builder.
      */
    public com.acvr.order.dto.OrderCreated.Builder clearOrderDate() {
      orderDate = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'costomerName' field.
      * @return The value.
      */
    public java.lang.CharSequence getCostomerName() {
      return costomerName;
    }

    /**
      * Sets the value of the 'costomerName' field.
      * @param value The value of 'costomerName'.
      * @return This builder.
      */
    public com.acvr.order.dto.OrderCreated.Builder setCostomerName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.costomerName = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'costomerName' field has been set.
      * @return True if the 'costomerName' field has been set, false otherwise.
      */
    public boolean hasCostomerName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'costomerName' field.
      * @return This builder.
      */
    public com.acvr.order.dto.OrderCreated.Builder clearCostomerName() {
      costomerName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'productName' field.
      * @return The value.
      */
    public java.lang.CharSequence getProductName() {
      return productName;
    }

    /**
      * Sets the value of the 'productName' field.
      * @param value The value of 'productName'.
      * @return This builder.
      */
    public com.acvr.order.dto.OrderCreated.Builder setProductName(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.productName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'productName' field has been set.
      * @return True if the 'productName' field has been set, false otherwise.
      */
    public boolean hasProductName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'productName' field.
      * @return This builder.
      */
    public com.acvr.order.dto.OrderCreated.Builder clearProductName() {
      productName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public java.lang.Double getAmount() {
      return amount;
    }

    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public com.acvr.order.dto.OrderCreated.Builder setAmount(double value) {
      validate(fields()[4], value);
      this.amount = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public com.acvr.order.dto.OrderCreated.Builder clearAmount() {
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderCreated build() {
      try {
        OrderCreated record = new OrderCreated();
        record.orderId = fieldSetFlags()[0] ? this.orderId : (java.lang.Long) defaultValue(fields()[0]);
        record.orderDate = fieldSetFlags()[1] ? this.orderDate : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.costomerName = fieldSetFlags()[2] ? this.costomerName : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.productName = fieldSetFlags()[3] ? this.productName : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.amount = fieldSetFlags()[4] ? this.amount : (java.lang.Double) defaultValue(fields()[4]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderCreated>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderCreated>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderCreated>
    READER$ = (org.apache.avro.io.DatumReader<OrderCreated>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
